"""modifed the app

Revision ID: 0adee7db2bd8
Revises: 8e0d9f853022
Create Date: 2026-02-12 01:58:17.038564

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Deterministic UUID for the default org used when backfilling existing rows
DEFAULT_ORG_ID = uuid.uuid5(uuid.NAMESPACE_DNS, "voice-agent-default-org.local")

# revision identifiers, used by Alembic.
revision: str = '0adee7db2bd8'
down_revision: Union[str, Sequence[str], None] = '8e0d9f853022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('business_context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # Insert default organization for backfilling existing rows
    op.execute(
        sa.text(
            "INSERT INTO organizations (id, name, slug, created_at, updated_at) "
            "VALUES (:id, 'Default', 'default', now(), now())"
        ).bindparams(id=DEFAULT_ORG_ID)
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('use_case', sa.Enum('lead_qualification', 'appointment_booking', 'support', 'custom', name='use_case_enum'), server_default='lead_qualification', nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('first_message', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('model_temperature', sa.Float(), nullable=True),
    sa.Column('voice_provider', sa.String(length=64), nullable=True),
    sa.Column('voice_id', sa.String(length=120), nullable=True),
    sa.Column('enabled_tool_names', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('vapi_assistant_id', sa.String(length=255), nullable=True),
    sa.Column('vapi_phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('cal_com_api_key', sa.Text(), nullable=True),
    sa.Column('cal_com_event_type_id', sa.Integer(), nullable=True),
    sa.Column('tool_api_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agents_tool_api_key'), 'agents', ['tool_api_key'], unique=True)
    op.create_index(op.f('ix_agents_vapi_assistant_id'), 'agents', ['vapi_assistant_id'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='org_role_enum'), server_default='member', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.add_column('bookings', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE bookings SET organization_id = :id WHERE organization_id IS NULL").bindparams(id=DEFAULT_ORG_ID))
    op.alter_column('bookings', 'organization_id', existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f('ix_bookings_organization_id'), 'bookings', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('calls', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE calls SET organization_id = :id WHERE organization_id IS NULL").bindparams(id=DEFAULT_ORG_ID))
    op.alter_column('calls', 'organization_id', existing_type=sa.UUID(), nullable=False)
    op.add_column('calls', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=False)
    op.create_index('idx_calls_org_vapi', 'calls', ['organization_id', 'vapi_call_id'], unique=False)
    op.create_index(op.f('ix_calls_agent_id'), 'calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_calls_organization_id'), 'calls', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_calls_org_vapi_call_id', 'calls', ['organization_id', 'vapi_call_id'])
    op.create_foreign_key(None, 'calls', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'calls', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('fit_checks', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE fit_checks SET organization_id = :id WHERE organization_id IS NULL").bindparams(id=DEFAULT_ORG_ID))
    op.alter_column('fit_checks', 'organization_id', existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f('ix_fit_checks_organization_id'), 'fit_checks', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'fit_checks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('handoffs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE handoffs SET organization_id = :id WHERE organization_id IS NULL").bindparams(id=DEFAULT_ORG_ID))
    op.alter_column('handoffs', 'organization_id', existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f('ix_handoffs_organization_id'), 'handoffs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'handoffs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('leads', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE leads SET organization_id = :id WHERE organization_id IS NULL").bindparams(id=DEFAULT_ORG_ID))
    op.alter_column('leads', 'organization_id', existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_leads_org_phone', 'leads', ['organization_id', 'phone'])
    op.create_foreign_key(None, 'leads', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('qualifications', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE qualifications SET organization_id = :id WHERE organization_id IS NULL").bindparams(id=DEFAULT_ORG_ID))
    op.alter_column('qualifications', 'organization_id', existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f('ix_qualifications_organization_id'), 'qualifications', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'qualifications', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('tool_calls', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tool_calls_organization_id'), 'tool_calls', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'tool_calls', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_calls', type_='foreignkey')
    op.drop_index(op.f('ix_tool_calls_organization_id'), table_name='tool_calls')
    op.drop_column('tool_calls', 'organization_id')
    op.drop_constraint(None, 'qualifications', type_='foreignkey')
    op.drop_index(op.f('ix_qualifications_organization_id'), table_name='qualifications')
    op.drop_column('qualifications', 'organization_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint('uq_leads_org_phone', 'leads', type_='unique')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.drop_column('leads', 'organization_id')
    op.drop_constraint(None, 'handoffs', type_='foreignkey')
    op.drop_index(op.f('ix_handoffs_organization_id'), table_name='handoffs')
    op.drop_column('handoffs', 'organization_id')
    op.drop_constraint(None, 'fit_checks', type_='foreignkey')
    op.drop_index(op.f('ix_fit_checks_organization_id'), table_name='fit_checks')
    op.drop_column('fit_checks', 'organization_id')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_constraint('uq_calls_org_vapi_call_id', 'calls', type_='unique')
    op.drop_index(op.f('ix_calls_organization_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_id'), table_name='calls')
    op.drop_index('idx_calls_org_vapi', table_name='calls')
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=True)
    op.drop_column('calls', 'agent_id')
    op.drop_column('calls', 'organization_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_organization_id'), table_name='bookings')
    op.drop_column('bookings', 'organization_id')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_agents_vapi_assistant_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_tool_api_key'), table_name='agents')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
