"""first databse push II

Revision ID: 8e0d9f853022
Revises: ef229a0ea674
Create Date: 2026-01-24 01:30:16.698779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e0d9f853022'
down_revision: Union[str, Sequence[str], None] = 'ef229a0ea674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), server_default='inbound_call', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcome_tag', sa.Enum('audit_booked', 'requested_info', 'callback_scheduled', 'parked', 'not_a_fit', 'no_answer', name='outcome_tag_enum'), nullable=True),
    sa.Column('outcome_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_version', sa.String(length=255), nullable=True),
    sa.Column('assistant_version', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calls_lead_id', 'calls', ['lead_id'], unique=False)
    op.create_index(op.f('ix_calls_lead_id'), 'calls', ['lead_id'], unique=False)
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('calendar_provider', sa.String(length=64), server_default='google_calendar', nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/London', nullable=False),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('booked', 'cancelled', 'rescheduled', name='booking_status_enum'), server_default='booked', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_calendar_event_id'), 'bookings', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_bookings_call_id'), 'bookings', ['call_id'], unique=False)
    op.create_index(op.f('ix_bookings_lead_id'), 'bookings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_table('fit_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('business_offer', sa.Text(), nullable=True),
    sa.Column('lead_sources', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('weekly_enquiries', sa.String(length=64), nullable=True),
    sa.Column('response_speed', sa.Enum('under_10_min', 'within_hour', 'same_day', 'later', 'unknown', name='response_speed_enum'), nullable=True),
    sa.Column('booking_method', sa.Text(), nullable=True),
    sa.Column('has_followup_system', sa.Boolean(), nullable=True),
    sa.Column('capacity_next_weeks', sa.Boolean(), nullable=True),
    sa.Column('primary_intent', sa.Enum('more_enquiries', 'enquiries_not_converting', 'stop_going_cold', 'unknown', name='primary_intent_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_checks_call_id'), 'fit_checks', ['call_id'], unique=False)
    op.create_index(op.f('ix_fit_checks_lead_id'), 'fit_checks', ['lead_id'], unique=False)
    op.create_table('handoffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('target_phone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('queued', 'completed', 'cancelled', name='handoff_status_enum'), server_default='queued', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoffs_call_id'), 'handoffs', ['call_id'], unique=False)
    op.create_index(op.f('ix_handoffs_lead_id'), 'handoffs', ['lead_id'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('diagnosis_tag', sa.Enum('leak_speed', 'leak_fragmentation', 'leak_followup', 'leak_booking', 'leak_traffic', name='leak_tag_enum'), nullable=True),
    sa.Column('one_sentence_summary', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('recommended_action', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_call_id'), 'qualifications', ['call_id'], unique=False)
    op.create_index(op.f('ix_qualifications_lead_id'), 'qualifications', ['lead_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_call_id'), 'tool_calls', ['call_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_name'), 'tool_calls', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_tool_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_call_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_qualifications_lead_id'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_call_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_handoffs_lead_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_call_id'), table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index(op.f('ix_fit_checks_lead_id'), table_name='fit_checks')
    op.drop_index(op.f('ix_fit_checks_call_id'), table_name='fit_checks')
    op.drop_table('fit_checks')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_lead_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_call_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_calendar_event_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_lead_id'), table_name='calls')
    op.drop_index('idx_calls_lead_id', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
